# Generated by Django 4.1.12 on 2023-11-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emergency",
            name="doctor",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="age",
            field=models.IntegerField(default=10),
        ),
    ]
